import subprocess
import tempfile
import os
from typing import Dict, List
from pathlib import Path
import httpx

async def create_migration_pr(
    owner: str,
    repo: str,
    github_token: str,
    breakage: Dict,
    fix_suggestion: str,
    affected_files: List[str],
) -> Dict:
    """
    1. Clone repo
    2. Create new branch: parsec/fix-{package}
    3. Apply Gemini's fix to affected files
    4. Commit + push
    5. Open PR via GitHub API
    """
    branch_name = f"parsec/fix-{breakage['package'].lower()}-{breakage['old_version']}"

    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp_dir:
        repo_url = f"https://x-access-token:{github_token}@github.com/{owner}/{repo}.git"

        # 1. Clone
        subprocess.run([
            "git", "clone", repo_url,
            "--depth", "10",
            tmp_dir,
        ], check=True, capture_output=True)

        # 2. Git config
        subprocess.run(["git", "config", "user.email", "parsec@dependency-analyser.dev"], cwd=tmp_dir)
        subprocess.run(["git", "config", "user.name", "Parsec Bot"], cwd=tmp_dir)

        # 3. Create new branch
        subprocess.run(["git", "checkout", "-b", branch_name], cwd=tmp_dir, check=True)

        # 4. Add migration notes as a file
        migration_file = Path(tmp_dir) / f"parsec_migration_{breakage['package']}.md"
        migration_file.write_text(
            f"# Migration: {breakage['package']} {breakage['old_version']} -> {breakage['new_version']}\n\n"
            f"## Breaking Change\n"
            f"- **Kind:** {breakage.get('kind', 'N/A')}\n"
            f"- **Location:** {breakage.get('location', 'N/A')}\n"
            f"- **Reason:** {breakage.get('reason', 'N/A')}\n\n"
            f"## AI-Suggested Fix\n\n"
            f"```python\n{fix_suggestion}\n```\n\n"
            f"## Affected Files\n"
            + "\n".join(f"- `{f}`" for f in affected_files)
            + "\n\n> Generated by [Parsec Dependency Analyser](https://github.com/Thijeshpraveen-V/dependency-analyser)",
            encoding='utf-8',
        )

        # 5. Stage + commit
        subprocess.run(["git", "add", "."], cwd=tmp_dir)
        subprocess.run([
            "git", "commit", "-m",
            f"fix: migration guide for {breakage['package']} {breakage['old_version']}→{breakage['new_version']}"
        ], cwd=tmp_dir, check=True)

        # 6. Push branch
        push = subprocess.run([
            "git", "push", "origin", branch_name
        ], capture_output=True, text=True, cwd=tmp_dir)

        if push.returncode != 0:
            return {"success": False, "error": push.stderr}

        # 7. Create PR via GitHub API
        pr = await _create_github_pr(
            owner=owner,
            repo=repo,
            github_token=github_token,
            branch_name=branch_name,
            breakage=breakage,
            fix_suggestion=fix_suggestion,
            affected_files=affected_files,
        )

        return {
            "success": True,
            "branch": branch_name,
            "pr_url": pr.get("html_url"),
            "pr_number": pr.get("number"),
            "pr_title": pr.get("title"),
        }


async def _create_github_pr(
    owner: str,
    repo: str,
    github_token: str,
    branch_name: str,
    breakage: Dict,
    fix_suggestion: str,
    affected_files: List[str],
) -> Dict:
    """Create a PR via GitHub API."""
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
    }

    pr_body = (
        f"## 🔍 Parsec Dependency Migration Report\n\n"
        f"### Package: `{breakage['package']}` `{breakage['old_version']}` → `{breakage['new_version']}`\n\n"
        f"| Field | Detail |\n"
        f"|-------|--------|\n"
        f"| Kind | `{breakage.get('kind', 'N/A')}` |\n"
        f"| Location | `{breakage.get('location', 'N/A')}` |\n"
        f"| Reason | {breakage.get('reason', 'N/A')} |\n\n"
        f"### 🤖 AI-Suggested Fix\n\n"
        f"```python\n{fix_suggestion}\n```\n\n"
        f"### 📁 Affected Files\n"
        + "\n".join(f"- `{f}`" for f in affected_files)
        + "\n\n"
        f"> **Generated by [Parsec](https://github.com/Thijeshpraveen-V/dependency-analyser)** "
        f"— AI-powered dependency migration tool using Griffe + Astra DB + Gemini\n\n"
        f"⚠️ *Please review the suggested changes carefully before merging.*"
    )

    async with httpx.AsyncClient() as client:
        resp = await client.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": f"fix: Migrate {breakage['package']} {breakage['old_version']} → {breakage['new_version']}",
                "body": pr_body,
                "head": branch_name,
                "base": "main",
                "draft": False,
            },
        )
        return resp.json()
